TASKS = [
    {
        "id": "DraftArchitecture",
        "label": "Draft architecture",
        "start": "M1Q3FY26",
        "deadline": "M2Q3FY26",
        "expected_duration": 2,
        "milestone": "Design",
        "priority": "high",
        "risk_level": "medium",
        "risk_type": "scope",
        "risk_mitigation": "Review the architecture with stakeholders before implementation starts.",
        "status": "complete",
        "description": "Produce the first architecture draft for the planner.",
        "project": "Planning System",
        "dependencies": [],
    },
    {
        "id": "DefineTaskSchema",
        "label": "Define task schema",
        "start": "M2Q3FY26",
        "deadline": "M2Q3FY26",
        "expected_duration": 1,
        "milestone": "Design",
        "priority": "high",
        "risk_level": "low",
        "risk_type": "requirements",
        "risk_mitigation": "Document field aliases and validate examples against the schema.",
        "status": "pending",
        "description": "Lock down the required task attributes and field aliases.",
        "project": "Planning System",
        "dependencies": ["DraftArchitecture"],
    },
]
