TASKS = [
    {
        "name": "Draft architecture",
        "start_date": "2026-04-01",
        "due_date": "2026-05-05",
        "expected_duration": 2,
        "milestone": "Design",
        "priority": "high",
        "risk_level": "medium",
        "risk_type": "scope",
        "risk_mitigation": "Review the architecture with stakeholders before implementation starts.",
        "status": "done",
        "description": "Produce the first architecture draft for the planner.",
        "project": "Planning System",
        "dependencies": [],
    },
    {
        "name": "Define task schema",
        "start_date": "2026-05-01",
        "due_date": "2026-05-07",
        "expected_duration": 1,
        "milestone": "Design",
        "priority": "high",
        "risk_level": "low",
        "risk_type": "requirements",
        "risk_mitigation": "Document field aliases and validate examples against the schema.",
        "status": "todo",
        "description": "Lock down the required task attributes and field aliases.",
        "project": "Planning System",
        "dependencies": ["Draft architecture"],
    },
]
